### ISSUE TITLE
Doesn't work under "N" preview 2.

### ISSUE THREAD

**Issue by neiljaywarner** [udacity/Advanced_Android_Development#56]
05-15 18:03:40.839 19870-19870/com.example.android.sunshine.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.example.android.sunshine.app, PID: 19870
                                                                                  android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class <unknown>
                                                                                  Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class <unknown>
                                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:431)
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                      at com.example.android.sunshine.app.ForecastAdapter.onCreateViewHolder(ForecastAdapter.java:117)
                                                                                      at com.example.android.sunshine.app.ForecastAdapter.onCreateViewHolder(ForecastAdapter.java:39)
                                                                                      at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5062)
                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4368)
                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4278)
                                                                                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1947)
                                                                                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1359)
                                                                                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1322)
                                                                                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
                                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1000)
                                                                                      at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:710)
                                                                                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:982)
                                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:723)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
05-15 18:03:40.840 19870-19870/com.example.android.sunshine.app E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:699)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2265)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1995)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6217)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6066)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:770)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
                                                                                   Caused by: android.content.res.Resources$NotFoundException: Drawable com.example.android.sunshine.app:drawable/touch_selector with resource ID #0x7f02006e
                                                                                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/touch_selector.xml from drawable resource ID #0x7f02006e
                                                                                      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:681)
                                                                                      at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:527)
                                                                                      at android.content.res.Resources.loadDrawable(Resources.java:855)
                                                                                      at android.content.res.TypedArray.getDrawable(TypedArray.java:924)
                                                                                      at android.view.View.<init>(View.java:4158)
                                                                                      at android.view.ViewGroup.<init>(ViewGroup.java:578)
                                                                                      at android.widget.FrameLayout.<init>(FrameLayout.java:97)
                                                                                      at android.widget.FrameLayout.<init>(FrameLayout.java:92)
                                                                                      at android.widget.FrameLayout.<init>(FrameLayout.java:88)
                                                                                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:431)
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                      at com.example.android.sunshine.app.ForecastAdapter.onCreateViewHolder(ForecastAdapter.java:117)
                                                                                      at com.example.android.sunshine.app.ForecastAdapter.onCreateViewHolder(ForecastAdapter.java:39)
                                                                                      at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5062)
                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4368)
                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4278)
                                                                                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1947)
                                                                                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1359)
                                                                                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1322)
                                                                                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
                                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1000)
05-15 18:03:40.843 19870-19870/com.example.android.sunshine.app E/AndroidRuntime:     at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:710)
                                                                                      at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                      at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:982)
                                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:723)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1737)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1581)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1490)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:699)
                                                                                      at android.view.View.layout(View.java:17450)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5540)
                                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2265)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1995)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6217)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6066)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:770)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.jumpToCurrentState()' on a null object reference
                                                                                      at android.graphics.drawable.LayerDrawable.jumpToCurrentState(LayerDrawable.java:1424)
                                                                                      at android.graphics.drawable.RippleDrawable.jumpToCurrentState(RippleDrawable.java:213)
                                                                                      at android.graphics.drawable.RippleDrawable.setVisible(RippleDrawable.java:335)
                                                                                      at android.graphics.drawable.DrawableContainer.initializeDrawableForDisplay(DrawableContainer.java:519)
                                                                                      at android.graphics.drawable.DrawableContainer.selectDrawable(DrawableContainer.java:470)
                                                                                      at android.graphics.drawable.StateListDrawable.onStateChange(StateListDrawable.java:104)
                                                                                      at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:118)
                                                                                      at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
05-15 18:03:40.843 19870-19870/com.example.android.sunshine.app E/AndroidRuntime:     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1165)
                                                                                      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1138)
                                                                                      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:671)
                                                                                      	... 79 more

**Comment by neiljaywarner** [comment]
Tried 7, doens't work, tried branch 6, works
