### ISSUE TITLE
Doesn't work in android version 6.0.1

### ISSUE THREAD

**Issue by mohammad1990** [udacity/Advanced_Android_Development#62]
**# crashes pretty much immediatley after opening**:
10-15 00:59:15.701 5096-5096/com.example.android.sunshine.app E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.example.android.sunshine.app, PID: 5096
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.sunshine.app/com.example.android.sunshine.app.MainActivity}: java.lang.SecurityException: uid 10058 cannot get secrets for accounts of type: sunshine.example.com
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7329)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                 Caused by: java.lang.SecurityException: uid 10058 cannot get secrets for accounts of type: sunshine.example.com
                                                                                    at android.os.Parcel.readException(Parcel.java:1621)
                                                                                    at android.os.Parcel.readException(Parcel.java:1574)
                                                                                    at android.accounts.IAccountManager$Stub$Proxy.getPassword(IAccountManager.java:694)
                                                                                    at android.accounts.AccountManager.getPassword(AccountManager.java:334)
                                                                                    at com.example.android.sunshine.app.sync.SunshineSyncAdapter.getSyncAccount(SunshineSyncAdapter.java:607)
                                                                                    at com.example.android.sunshine.app.sync.SunshineSyncAdapter.initializeSyncAdapter(SunshineSyncAdapter.java:646)
                                                                                    at com.example.android.sunshine.app.MainActivity.onCreate(MainActivity.java:92)
                                                                                    at android.app.Activity.performCreate(Activity.java:6904)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7329) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by matijuguera** [comment]
could u solve this problem?
